# Generated by Django 4.2.11 on 2024-03-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.TextField(max_length=150)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('designation', models.CharField(choices=[('Manager', 'Manager'), ('Software Developer', 'SDE'), ('intern', 'itr')], max_length=20)),
                ('comapany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
